name: Run eBPF Supply Chain Detector

on:
  push:
    branches: [main]

jobs:
  run-ebpf:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest image
        run: docker pull rohitcoder/supplychain:latest

      - name: Run eBPF supply chain detector
        run: |
          docker run --rm --privileged \
            -v /sys:/sys \
            -v /proc:/proc \
            -v /lib/modules:/lib/modules \
            -v /usr/src:/usr/src \
            rohitcoder/supplychain:latest
